services:
  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    image: 3-tier:mysql-v1

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: 3-tier:backend-v1

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: 3-tier:frontend-v1
