services:
  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    image: java-mysql:v1

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: java-backend:v1

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: java-frontend:v1
