services:
  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    image: siva9666/expense-mysql-v1

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: siva9666/expense-backend:java

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: siva9666/expense-frontend:java

