services:
  backend:
    image: siva9666/expense-backend:java
    container_name: backend
    environment:
      - DB_HOST=test-db.konkas.tech
      - DB_USER=crud 
      - DB_PASSWD=CrudApp@1
      - DB_PORT=3306
      - DATABASE=java_crud_app
    restart: on-failure
    networks:
      - expense
  frontend:
    image: siva9666/expense-frontend:java
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    restart: on-failure
    networks:
      - expense
networks:
  expense:
    driver: bridge
